import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export const getStaticProps = async () => {
  const GQL_API = `http://frp.vlb.mybluehost.me/graphql`;
  const GQL_QUERY = `
    query{
      posts{
        nodes {
          postId
          title
          date
          featuredImage {
            node {
              sourceUrl
            }
          }
        }
      }
    }
    `;
  const res = await fetch(GQL_API, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      query: GQL_QUERY,
    }),
  });

  const result = await res.json();
  //console.log(result.data.posts.nodes);

  return {
    props: { blogs: result.data.posts.nodes },
  };
};
export default function Blogs({ blogs }) {
  var options = { year: "numeric", month: "short", day: "numeric" };
  return (
    <>
      <Head>
        <title>Thomson Reuters | Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./tr_favicon.ico" />
      </Head>

      <main>
        <nav className="nav-bar">
          <img src="./tr_logo.png" className="app-logo" alt="TR logo" />
          <h1 className="app-title"> Thomson Reuters GrpahQL POC NextJS App</h1>
          <ul className="nav-pages">
            <li>
              <Link href="/">
                <a>Home</a>
              </Link>
            </li>
            <li>
              <Link href="/blogs">
                <a>Blogs</a>
              </Link>
            </li>
            <li>
              <Link href="/products">
                <a>Products</a>
              </Link>
            </li>
          </ul>
        </nav>
        <body className="body">
          <div className="blogs">
            <h2>Thomson Reuter Institute Blogs</h2>
            <p>
              The Thomson Reuters Institute brings together people from across
              the legal, corporate, tax & accounting, and government communities
              to ignite conversation and debate, make sense of the latest events
              and trends, and provide essential guidance on the opportunities
              and challenges facing their world today.
            </p>
          </div>
          {blogs.map((blog) => {
            var d = new Date(blog.date);
            return (
              <Link
                href={"/blogs/" + blog.title.toLowerCase().replace(/\s+/g, "-")}
                key={blog.postId}
              >
                <a>
                  <img src={blog.featuredImage.node.sourceUrl}></img>
                  <h3> {blog.title} </h3>
                  <p>{d.toLocaleDateString("en-US", options)}</p>
                </a>
              </Link>
            );
          })}
        </body>
      </main>
    </>
  );
}
