import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Blogs() {
  return (
    <>
      <Head>
        <title>Thomson Reuters | Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./tr_favicon.ico" />
      </Head>

      <main>
        <nav className="nav-bar">
          <img src="./tr_logo.png" className="app-logo" alt="TR logo" />
          <h1 className="app-title"> Thomson Reuters GrpahQL POC NextJS App</h1>
          <ul className="nav-pages">
            <li>
              <Link href="/blogs">
                <a>Blogs</a>
              </Link>
            </li>
            <li>
              <Link href="/products">
                <a>Products</a>
              </Link>
            </li>
          </ul>
        </nav>
        <body className="body">
          <div className="blogs">
            <h2>Thomson Reuter Institute Blogs</h2>
            <p>
              The Thomson Reuters Institute brings together people from across
              the legal, corporate, tax & accounting, and government communities
              to ignite conversation and debate, make sense of the latest events
              and trends, and provide essential guidance on the opportunities
              and challenges facing their world today.
            </p>
          </div>
        </body>
      </main>
    </>
  );
}
