import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import parse from "html-react-parser";

export const getStaticPaths = async () => {
  const GQL_API = "http://localhost:3030";
  const GQL_QUERY = `
    query{
      products{
        title
        author
        publisher
        publication_date
        image
        text
        id
        price
        jurisdiction
        ibsn
      }
    }
  `;
  const res = await fetch(GQL_API, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      query: GQL_QUERY,
    }),
  });
  const data = await res.json();
  console.log(data);
  const paths = data.data.products.map((product) => {
    return {
      params: { id: product.id.toString() },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async (context) => {
  const id = context.params.id;
  const GQL_API = "http://localhost:3030";
  const GQL_QUERY = `
    query{
      products(id: ${id}){
        title
        author
        publisher
        publication_date
        image
        text
        id
        price
        jurisdiction
        ibsn
      }
    }
  `;

  const res = await fetch(GQL_API, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      query: GQL_QUERY,
    }),
  });
  const data = await res.json();

  return {
    props: { product: data.data.products[0] },
  };
};

const Details = ({ product }) => {
  var options = { year: "numeric", month: "short", day: "numeric" };
  var d = new Date(product.publication_date);
  return (
    <>
      <Head>
        <title>Thomson Reuters | Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../tr_favicon.ico" />
      </Head>
      <main>
        <nav className="nav-bar">
          <img src="../tr_logo.png" className="app-logo" alt="TR logo" />
          <h1 className="app-title"> Thomson Reuters GraphQL POC NextJS App</h1>
          <ul className="nav-pages">
            <li>
              <Link href="/">
                <a>Home</a>
              </Link>
            </li>
            <li>
              <Link href="/blogs">
                <a>Blogs</a>
              </Link>
            </li>
            <li>
              <Link href="/products">
                <a>Products</a>
              </Link>
            </li>
          </ul>
        </nav>
        <body className="body">
          <div className="product">
            <h1>Details Page</h1>
            <h2>{product.title}</h2>
            <img
              src={product.image}
              alt="Product image"
              width="200"
              height="200"
            ></img>
            <div>{parse(product.text)}</div>
            <br></br>
            <div>
              <h4>
                {"Publication date: " + d.toLocaleDateString("en-US", options)}
              </h4>
              <h4>{"IBSN: " + product.ibsn}</h4>
              <h4>{"Price: $" + product.price}</h4>
              <h4>{"Author: " + product.author}</h4>
              <h4>{"Publisher: " + product.publisher}</h4>
              <h4>{"Jurisdiction: " + product.jurisdiction}</h4>
            </div>
          </div>
        </body>
      </main>
    </>
  );
};

export default Details;
