import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
export const getStaticProps = async () => {
  const GQL_API = 'http://localhost:3030';
  const GQL_QUERY = `
  `
  const res = fetch(GQL_API, {
    
  })
}
export default function Products() {
  return (
    <>
      <Head>
        <title>Thomson Reuters | Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./tr_favicon.ico" />
      </Head>

      <main>
        <nav className="nav-bar">
          <img src="./tr_logo.png" className="app-logo" alt="TR logo" />
          <h1 className="app-title"> Thomson Reuters GrpahQL POC NextJS App</h1>
          <ul className="nav-pages">
            <li>
              <Link href="/blogs">
                <a>Blogs</a>
              </Link>
            </li>
            <li>
              <Link href="/products">
                <a>Products</a>
              </Link>
            </li>
          </ul>
        </nav>
        <body className="body">
          <div className="products">
            <h2>Thomson Reuter Books and Products</h2>
            <p>
              Explore the several books and products offered by Thomson Reuters.
            </p>
          </div>
        </body>
      </main>
    </>
  );
}
